### PR TITLE
[Test] reallocate person

### PR DESCRIPTION
**Pull request by ThaDeveloper**

### CODE REVIEW

**Comment by Elbertbiggs360** [comment]
Your tests dont cover the dojo file which is observably where your functionality is. You might want to include it in your testing otherwise your coverage isnt a true reflection of the implemented functionality

**Comment by ThaDeveloper** [comment]
How do I add it here >> 'nosetests --with-coverage --cover-package=src'

**Comment by Elbertbiggs360** [comment]
I think it makes more sense to move the file into the src package

**Comment by ThaDeveloper** [comment]
cool, will do that

**Pull request merged**
